In [1]:
import warnings
warnings.filterwarnings('ignore')
%config Computer.use_jedi = False
import numpy as np

def pprint(arr):
    print('type: {}'.format(type(arr)))
    print('shape: {}, dimension: {}, dtype: {}'.format(arr.shape, arr.ndim, arr.dtype))
    print('numpy 배열의 데이터\n', arr, sep='')

numpy 파일 입출력  

numpy는 배열 객체를 바이너리(2진) 파일 또는 텍스트 파일에 저장하고 로딩하는 기능을 제공한다.

In [ ]:
# 메소드 이름        기능                                                      파일 포맷
# save()             numpy 배열 객체 1개를 바이너리 파일로 저장한다.           바이너리 
# savez()            numpy 배열 객체 여러개를 바이너리 파일로 저장한다.        바이너리  
# load()             numpy 배열 저장 파일로부터 배열 객체를 읽어온다.          바이너리
# -------------------------------------------------------------------------------------
# savetxt()          numpy 배열 객체를 텍스트 파일로 저장한다.                 텍스트
# loadtxt()          텍스트 파일에 저장된 numpy 배열 객체를 읽어온다.          텍스트

In [34]:
a = np.random.randint(0, 10, (2, 3))
print(a)
b = np.random.randint(0, 10, (2, 3))
print(b)

[[8 4 0]
 [1 0 7]]
[[7 0 2]
 [8 2 4]]


In [ ]:
# numpy 배열 객체를 바이너리 파일로 저장

In [40]:
# save(), savez() 메소드를 사용해서 배열 객체를 바이너리(2진) 형태의 파일로 저장할 수 있다.
# save(): 배열 1개를 저장한다.(확장명 => npy)
# savez(): 배열 여러개를 저장한다.(확장명 => npz)

# a배열을 바이너리 파일로 저장한다. 
# save('경로명', 배열명)
# 확장명이 정해져 있기 때문에 my_array1 뒤에 아무것도 적지 않는다.
np.save('./output/my_array1', a)

# a, b 배열을 바이너리 파일로 저장한다.
# savez('경로명', 배열명1, 배열명)
np.savez('./output/my_array2', a, b)

바이너리 파일로 저장된 numpy 배열 객체 읽어오기

In [41]:
# load() 메소드로 npy, npz 파일로부터 데이터를 읽어올 수 있다.
# npy 파일 읽기, 저장할 때는 확장명을 쓰지 않아도 알아서 저장이 되지만 읽어올 때는 load() 메소드를 동일하게 사용하기 때문에 npy인지 npz인지 구분하기 위해 확장명을 써줘야 한다.
# load('경로명')
print(np.load('./output/my_array1.npy'))

[[8 4 0]
 [1 0 7]]


In [44]:
# npz 파일 읽기
print(np.load('./output/my_array2.npz'))
npzFile = np.load('./output/my_array2.npz')
print(npzFile['arr_0'])
print(npzFile['arr_1'])

[[8 4 0]
 [1 0 7]]
[[7 0 2]
 [8 2 4]]


numpy 배열 객체를 텍스트 파일로 저장

In [45]:
c = np.random.random((3, 4))
print(c)

[[0.7902216  0.78029875 0.36606875 0.01527556]
 [0.5363866  0.30188641 0.9569258  0.92842473]
 [0.47779714 0.00870058 0.84649497 0.50883268]]


In [47]:
# 텍스트 파일은 확장명이 txt인 파일을 의미하는 것이 아니고 확장명이 csv 또는 tsv인 파일을 의미한다.
# savetxt() 메소드로 배열 객체를 텍스트 파일 형태로 저장할 수 있다.
# savetxt('경로명', 배열명, delimiter='구분자')
np.savetxt('./output/saved.csv', c, delimiter=',') # csv 파일은 데이터를 ','로 구분한다.
np.savetxt('./output/saved.tsv', c, delimiter='\t') # tsv 파일은 데이터를 'tab'로 구분한다.

텍스트 파일로 저장된 numpyy 배열 객체 읽어오기

In [50]:
# loadtxt() 메소드로 텍스트 파일로 저장된 numpy 배열 객체를 읽어올 수 있다.
# loadtxt('경로명', dtype, delimiter='구분자')
print(np.loadtxt('./output/saved.csv', dtype=np.float, delimiter=','))
print(np.loadtxt('./output/saved.tsv', dtype=np.int, delimiter='\t'))

[[0.7902216  0.78029875 0.36606875 0.01527556]
 [0.5363866  0.30188641 0.9569258  0.92842473]
 [0.47779714 0.00870058 0.84649497 0.50883268]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


배열(행렬) 연산 - 산술 연산

In [54]:
a = np.arange(1, 10).reshape(3, 3)
pprint(a)
b = np.arange(9, 0, -1).reshape(3, 3)
pprint(b)

type: <class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype: int32
numpy 배열의 데이터
[[1 2 3]
 [4 5 6]
 [7 8 9]]
type: <class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype: int32
numpy 배열의 데이터
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [56]:
# 덧셈: +, add()
print(a + b)
print(np.add(a, b))

[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [58]:
# 뺄셈: -, subtract()
print(a - b)
print(np.subtract(a,b))

[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [60]:
# 곱셈: *, multiply
print(a * b)
print(np.multiply(a, b))

[[ 9 16 21]
 [24 25 24]
 [21 16  9]]
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [64]:
# 나눗셈: /, divide
print(a / b)
print(np.divide(a, b))

[[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]
[[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]


In [66]:
print(a // b)
print(a % b)

[[0 0 0]
 [0 1 1]
 [2 4 9]]
[[1 2 3]
 [4 0 2]
 [1 0 0]]


In [67]:
# 지수
print(np.exp(a))

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]


In [68]:
# 제곱근
print(np.sqrt(a))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


In [70]:
# 삼각함수
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]
[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]
 [ 0.75390225 -0.14550003 -0.91113026]]
[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]
 [ 0.87144798 -6.79971146 -0.45231566]]


In [71]:
# 로그
print(np.log(a))

[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]
 [1.94591015 2.07944154 2.19722458]]


In [72]:
# 행렬의 내적
print(np.dot(a, b))

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


배열(행렬) 연산 - 비교 연산

In [74]:
# 배열 요소별 비교: >, >=, <=, ==, !=
print(a == b)

[[False False False]
 [False  True False]
 [False False False]]


In [76]:
# 배열 전체 비교: array_equal() 메소드
print(np.array_equal(a, b))

False


집계 함수  
numpy의 모든 집계 함수는 axis를 기준으로 계산하며 집계 함수에 axis를 지정하지 않으면 None이 기본값으로 사용된다.

In [77]:
a = np.arange(1, 10).reshape(3, 3)
pprint(a)

type: <class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype: int32
numpy 배열의 데이터
[[1 2 3]
 [4 5 6]
 [7 8 9]]


합계: numpy배열.sum(), np.sum(numpy배열)

In [81]:
# axis=None
# axis=None은 전체 배열을 행과 열을 구분하지 않고 전체 합계를 계산한다. 생략시 기본값으로 사용된다.
print(a.sum())
print(a.sum(axis=None))
print(np.sum(a))
print(np.sum(a, axis=None))

45
45
45
45


<img src="./images/numpyImage02.jpg" align="left" width="200">

In [83]:
# axis = 0
# axis = 0은 열 방향의 합계를 의미한다.
print(a.sum(axis=0))
print(np.sum(a, axis=0))

[12 15 18]
[12 15 18]


<img src="./images/numpyImage03.jpg" align="left" width="200">

In [85]:
# axis = 1
# axis = 1은 행 방향의 합계를 의미한다.
print(a.sum(axis=1))
print(np.sum(a, axis=1))

[ 6 15 24]
[ 6 15 24]


<img src="./images/numpyImage04.jpg" align="left" width="200">

최댓값: numpy배열.max(), np.max(numpy배열), 최소값: numpy배열.min(), np.min(numpy.배열)

In [87]:
print(a.max()) # print(a.max(axis=None))
print(np.max(a)) # print(np.max(a, axis=None))
print(a.min()) # print(a.min(axis=None))
print(np.min(a)) # print(np.min(a, axis=None))

9
9
1
1


In [88]:
print(a.max(axis=0))
print(np.max(a, axis=0))
print(a.min(axis=1)) 
print(np.min(a, axis=1))

[7 8 9]
[7 8 9]
[1 4 7]
[1 4 7]


In [89]:
print(a.max(axis=1))
print(np.max(a, axis=1))
print(a.min(axis=1)) 
print(np.min(a, axis=1))

[3 6 9]
[3 6 9]
[1 4 7]
[1 4 7]


누적 합계: numpy배열.cumsum(), np.cumsum(numpy배열)

In [91]:
print(a.cumsum())
print(np.cumsum(a))

[ 1  3  6 10 15 21 28 36 45]
[ 1  3  6 10 15 21 28 36 45]


In [93]:
print(a.cumsum(axis=0))
print(np.cumsum(a, axis=0))

[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]
[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]


In [94]:
print(a.cumsum(axis=1))
print(np.cumsum(a, axis=1))

[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]
[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]


평균: numpy배열.mean(), np.mean(numpy배열)

In [95]:
print(a.mean())
print(np.mean(a))

5.0
5.0


In [96]:
print(a.mean(axis=0))
print(np.mean(a, axis=0))

[4. 5. 6.]
[4. 5. 6.]


In [97]:
print(a.mean(axis=1))
print(np.mean(a, axis=1))

[2. 5. 8.]
[2. 5. 8.]


중위수: np.median(numpy.배열)

In [99]:
print(np.median(a))
print(np.mean(a, axis=0))
print(np.mean(a, axis=1))

5.0
[4. 5. 6.]
[2. 5. 8.]


상관계수: np.corrcoef(numpy.배열)

In [101]:
print(np.corrcoef(a, b)) # axis는 쓰면 에러가 난다.

[[ 1.  1.  1. -1. -1. -1.]
 [ 1.  1.  1. -1. -1. -1.]
 [ 1.  1.  1. -1. -1. -1.]
 [-1. -1. -1.  1.  1.  1.]
 [-1. -1. -1.  1.  1.  1.]
 [-1. -1. -1.  1.  1.  1.]]


표준편차: numpy배열.std(), np.std(numpy배열)

In [103]:
print(a.std())
print(np.std(a))

2.581988897471611
2.581988897471611


In [104]:
print(a.std(axis=0))

[2.44948974 2.44948974 2.44948974]


In [106]:
print(np.std(a, axis=0))

[2.44948974 2.44948974 2.44948974]


In [107]:
print(a.std(axis=1))
print(np.std(a, axis=1))

[0.81649658 0.81649658 0.81649658]
[0.81649658 0.81649658 0.81649658]
